#-------------------------------------------------------------------------------
#
# This file is part of the SamlBundle.
#
# (c) Paulo Dias <dias.paulo@gmail.com>
#
#-------------------------------------------------------------------------------
saml_login:
    path: /login-saml
    defaults:
        _controller: PDias\SamlBundle\Controller\SecurityController::loginAction

saml_login_check:
    path: /login-check-saml
    defaults:
        _controller: PDias\SamlBundle\Controller\SecurityController::checkAction

saml_logout:
    path: /logout-saml
    defaults:
        _controller: PDias\SamlBundle\Controller\SecurityController::logoutAction
